version: '2'
services:
    zoo-1:
        image: zookeeper
        restart: always
        ports:
          - "2181:2181"
        volumes:
            - ./data/zoo-1:/opt/persist
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_LOG_DIR: /opt/persist/logs
            ZOO_DATA_DIR: /opt/persist/data
